[group]
id = "holostars"
name = "Holostars"
parent = "hololive"
order = 4


# Official channels

[[streamer]]
name = "Holostars Official"
channel_id = "UCWsfcksUUpoEvhia0_ut0bA"
channel_name = "holostars ホロスターズ - VTuber Group"
twitter = "holostarstv"


# 1st Generation

[[streamer]]
name = "Hanasaki Miyabi"
channel_id = "UC6t3-_N8A6ME1JShZHHqOMw"
channel_name = "Miyabi Ch. 花咲みやび"
twitter = "miyabihanasaki"
aliases = ["miyabi", "みやび"]

[[streamer]]
name = "Rikkaroid"
channel_id = "UC9mf_ZVpouoILRY9NUIaK-w"
channel_name = "Rikka ch.律可"
twitter = "rikkaroid"
aliases = ["rikka", "りっか", "律可"]

[[streamer]]
name = "Arurandeisu"
channel_id = "UCKeAhJvy8zgXWbh9duVjIaQ"
channel_name = "Aruran Ch. アルランディス"
twitter = "arurandeisu"
aliases = ["aruran"]

[[streamer]]
name = "Kanade Izuru"
channel_id = "UCZgOv3YDEs-ZnZWDYVwJdmA"
channel_name = "Izuru Ch. 奏手イヅル"
twitter = "kanadeizuru"
aliases = ["izuru"]
free_chat_streams = true


# 2nd Generation

[[streamer]]
name = "Yukoku Roberu"
channel_id = "UCANDOlYTJT7N5jlRC3zfzVA"
channel_name = "Roberu Ch. 夕刻ロベル"
twitter = "yukokuroberu"
aliases = ["winning son", "roberu", "ロベル"]

[[streamer]]
name = "Kishido Temma"
channel_id = "UCGNI4MENvnsymYjKiZwv9eg"
channel_name = "Temma Ch. 岸堂天真"
twitter = "kishidotemma"
aliases = ["temma", "天真", "てんま"]

[[streamer]]
name = "Astel Leda"
channel_id = "UCNVEsYbiZjH5QLmGeSgTSzg"
channel_name = "astel ch.アステル"
twitter = "astelleda"
aliases = ["astel", "アステル"]


# 3rd Generation

[[streamer]]
name = "Kageyama Shien"
channel_id = "UChSvpZYRPh0FvG4SJGSga3g"
channel_name = "Shien Ch.影山シエン"
twitter = "kageyamashien"
aliases = ["shien", "シエン"]

[[streamer]]
name = "Aragami Oga"
channel_id = "UCwL7dgTxKo8Y4RFIKWaf8gA"
channel_name = "Oga Ch.荒咬オウガ"
twitter = "aragamioga"
aliases = ["oga"]


# UPROAR!!

[[streamer]]
name = "Yatogami Fuma"
channel_id = "UCc88OV45ICgHbn3ZqLLb52w"
channel_name = "Fuma Ch. 夜十神封魔 - UPROAR!! -"
twitter = "yatogamifuma"
aliases = ["fuma"]

[[streamer]]
name = "Utsugi Uyu"
channel_id = "UCgRqGV1gBf2Esxh0Tz1vxzw"
channel_name = "Uyu Ch. 羽継烏有 - UPROAR!! -"
twitter = "utsugiuyu"
aliases = ["uyu"]

[[streamer]]
name = "Hizaki Gamma"
channel_id = "UCkT1u65YS49ca_LsFwcTakw"
channel_name = "Gamma Ch. 緋崎ガンマ - UPROAR!! -"
twitter = "hizakigamma"
aliases = ["gamma"]

[[streamer]]
name = "Minase Rio"
channel_id = "UCdfMHxjcCc2HSd9qFvfJgjg"
channel_name = "Rio Ch. 水無世燐央 - UPROAR!! -"
twitter = "minaserioch"
aliases = ["rio"]


# English: TEMPUS

[[streamer]]
name = "Regis Altare"
channel_id = "UCyxtGMdWlURZ30WSnEjDOQw"
channel_name = "Regis Altare Ch. HOLOSTARS-EN"
twitter = "regisaltare"
aliases = ["Regis"]

[[streamer]]
name = "Magni Dezmond"
channel_id = "UC7MMNHR-kf9EN1rXiesMTMw"
channel_name = "Magni Dezmond Ch. HOLOSTARS-EN"
twitter = "magnidezmond"
aliases = ["Magni"]

[[streamer]]
name = "Axel Syrios"
channel_id = "UC2hx0xVkMoHGWijwr_lA01w"
channel_name = "Axel Syrios Ch. HOLOSTARS-EN"
twitter = "axelsyrios"
aliases = ["Axel"]

[[streamer]]
name = "Noir Vesper"
channel_id = "UCDRWSO281bIHYVi-OV3iFYA"
channel_name = "Noir Vesper Ch. HOLOSTARS-EN"
twitter = "noirvesper_en"
aliases = ["Noir"]

[[streamer]]
name = "Josuiji Shinri"
channel_id = "UCMqGG8BRAiI1lJfKOpETM_w"
channel_name = "Josuiji Shinri Ch. HOLOSTARS-EN"
twitter = "josuijishinri"
aliases = ["Josuiji"]

[[streamer]]
name = "Banzoin Hakka"
channel_id = "UC7gxU6NXjKF1LrgOddPzgTw"
channel_name = "Banzoin Hakka Ch. HOLOSTARS-EN"
twitter = "banzoinhakka"
aliases = ["Banzoin"]

[[streamer]]
name = "Machina X Flayon"
channel_id = "UC060r4zABV18vcahAWR1n7w"
channel_name = "Machina X Flayon Ch. HOLOSTARS-EN"
twitter = "machinaxflayon"
aliases = ["Machina", "Flayon", "Flay"]

[[streamer]]
name = "Gavis Bettel"
channel_id = "UCHP4f7G2dWD4qib7BMatGAw"
channel_name = "Gavis Bettel Ch. HOLOSTARS-EN"
twitter = "gavisbettel"
aliases = ["Gavis"]


# English: ARMIS

[[streamer]]
name = "Jurard T Rexford"
channel_id = "UCTVSOgYuSWmNAt-lnJPkEEw"
channel_name = "Jurard T Rexford Ch. HOLOSTARS-EN"
twitter = "jurardtrexford"
aliases = ["Jurard", "Rexford"]

[[streamer]]
name = "Goldbullet"
channel_id = "UCJv02SHZgav7Mv3V0kBOR8Q"
channel_name = "Goldbullet Ch. HOLOSTARS-EN"
twitter = "goldbullet_en"

[[streamer]]
name = "Octavio"
channel_id = "UCLk1hcmxg8rJ3Nm1_GvxTRA"
channel_name = "Octavio Ch. HOLOSTARS-EN"
twitter = "octavio_holo"

[[streamer]]
name = "Crimzon Ruze"
channel_id = "UCajbFh6e_R8QZdHAMbbi4rQ"
channel_name = "Crimzon Ruze Ch. HOLOSTARS-EN"
twitter = "crimzonruze"
aliases = ["Crimzon", "Ruze"]
