[group]
id = "holostars"
name = "Holostars"
parent = "hololive"
order = 4


# Official channels

[[streamer]]
name = "Holostars Official"
channel_id = "UCWsfcksUUpoEvhia0_ut0bA"
channel_name = "holostars ホロスターズ - VTuber Group"
twitter = "holostarstv"

[[streamer]]
name = "HOLOSTARS English"
channel_id = "UCJxZpzx4wHzEYD-eCiZPikg"
twitter = "HOLOSTARSen"


# HOLOSTARS 1st Gen

[[streamer]]
name = "Kanade Izuru"
channel_id = "UCZgOv3YDEs-ZnZWDYVwJdmA"
channel_name = "Izuru Ch. 奏手イヅル"
twitter = "kanadeizuru"
twitch = "kanadeizuru_holostars"
aliases = ["izuru"]
free_chat_streams = true


# HOLOSTARS 2nd Gen (SunTempo)

[[streamer]]
name = "Yukoku Roberu"
channel_id = "UCANDOlYTJT7N5jlRC3zfzVA"
channel_name = "Roberu Ch. 夕刻ロベル"
twitter = "yukokuroberu"
twitch = "yukokuroberu_holostars"
aliases = ["winning son", "roberu", "ロベル"]

[[streamer]]
name = "Astel Leda"
channel_id = "UCNVEsYbiZjH5QLmGeSgTSzg"
channel_name = "astel ch.アステル"
twitter = "astelleda"
aliases = ["astel", "アステル"]


# HOLOSTARS 3rd Gen (TriNero)

[[streamer]]
name = "Aragami Oga"
channel_id = "UCwL7dgTxKo8Y4RFIKWaf8gA"
channel_name = "Oga Ch.荒咬オウガ"
twitter = "aragamioga"
twitch = "aragamioga_holostars"
aliases = ["oga"]


# HOLOSTARS UPROAR!!

[[streamer]]
name = "Yatogami Fuma"
channel_id = "UCc88OV45ICgHbn3ZqLLb52w"
channel_name = "Fuma Ch. 夜十神封魔 - UPROAR!! -"
twitter = "yatogamifuma"
aliases = ["fuma"]

[[streamer]]
name = "Utsugi Uyu"
channel_id = "UCgRqGV1gBf2Esxh0Tz1vxzw"
channel_name = "Uyu Ch. 羽継烏有 - UPROAR!! -"
twitter = "utsugiuyu"
twitch = "utsugiuyu_uproar"
aliases = ["uyu"]


# HOLOSTARS English -TEMPUS- HQ

[[streamer]]
name = "Regis Altare"
channel_id = "UCyxtGMdWlURZ30WSnEjDOQw"
channel_name = "Regis Altare Ch. HOLOSTARS-EN"
twitter = "regisaltare"
twitch = "regisaltare_holostars_en"
aliases = ["Regis"]

[[streamer]]
name = "Axel Syrios"
channel_id = "UC2hx0xVkMoHGWijwr_lA01w"
channel_name = "Axel Syrios Ch. HOLOSTARS-EN"
twitter = "axelsyrios"
twitch = "axelsyrios"
aliases = ["Axel"]


# HOLOSTARS English -TEMPUS- Vanguard

[[streamer]]
name = "Josuiji Shinri"
channel_id = "UCMqGG8BRAiI1lJfKOpETM_w"
channel_name = "Josuiji Shinri Ch. HOLOSTARS-EN"
twitter = "josuijishinri"
twitch = "josuijishinri"
aliases = ["Josuiji"]

[[streamer]]
name = "Banzoin Hakka"
channel_id = "UC7gxU6NXjKF1LrgOddPzgTw"
channel_name = "Banzoin Hakka Ch. HOLOSTARS-EN"
twitter = "banzoinhakka"
twitch = "banzoinhakka"
aliases = ["Banzoin"]

[[streamer]]
name = "Machina X Flayon"
channel_id = "UC060r4zABV18vcahAWR1n7w"
channel_name = "Machina X Flayon Ch. HOLOSTARS-EN"
twitter = "machinaxflayon"
twitch = "machinaxflayon"
aliases = ["Machina", "Flayon", "Flay"]

[[streamer]]
name = "Gavis Bettel"
channel_id = "UCHP4f7G2dWD4qib7BMatGAw"
channel_name = "Gavis Bettel Ch. HOLOSTARS-EN"
twitter = "gavisbettel"
twitch = "gavisbettel"
aliases = ["Gavis"]


# HOLOSTARS English -ARMIS-

[[streamer]]
name = "Jurard T Rexford"
channel_id = "UCTVSOgYuSWmNAt-lnJPkEEw"
channel_name = "Jurard T Rexford Ch. HOLOSTARS-EN"
twitter = "jurardtrexford"
aliases = ["Jurard", "Rexford"]

[[streamer]]
name = "Goldbullet"
channel_id = "UCJv02SHZgav7Mv3V0kBOR8Q"
channel_name = "Goldbullet Ch. HOLOSTARS-EN"
twitter = "goldbullet_en"

[[streamer]]
name = "Octavio"
channel_id = "UCLk1hcmxg8rJ3Nm1_GvxTRA"
channel_name = "Octavio Ch. HOLOSTARS-EN"
twitter = "octavio_holo"
twitch = "octavioholo"

[[streamer]]
name = "Crimzon Ruze"
channel_id = "UCajbFh6e_R8QZdHAMbbi4rQ"
channel_name = "Crimzon Ruze Ch. HOLOSTARS-EN"
twitter = "crimzonruze"
twitch = "crimzonruze"
aliases = ["Crimzon", "Ruze"]
