[group]
id = "hololive-jp"
name = "Hololive JP"
parent = "hololive"
order = 1


# Official channels

[[streamer]]
name = "Hololive DEV_IS"
channel_id = "UC10wVt6hoQiwySRhz7RdOUA"
channel_name = "hololive DEV_IS"
twitter = "reglossofficial"


# 0th Generation

[[streamer]]
name = "AZKi"
channel_id = "UC0TXe_LYZ4scaW2XMyi5_kw"
channel_name = "AZKi Channel"
twitter = "AZKi_VDiVA"

[[streamer]]
name = "Hoshimachi Suisei"
channel_id = "UC5CwaMl1eIgY8h02uZw7u8A"
channel_name = "Suisei Channel"
twitter = "suisei_hosimati"
aliases = ["suisei", "suichan", "sui-chan", "すいせい", "すいちゃん"]

[[streamer]]
name = "Roboco-san"
channel_id = "UCDqI2jOz0weumE8s7paEk6g"
channel_name = "Roboco Ch. - ロボ子"
twitter = "robocosan"
twitch = "robocosan_hololive"
aliases = ["roboco", "ロボ子"]

[[streamer]]
name = "Sakura Miko"
channel_id = "UC-hM6YJuNYVAmUWxeIr9FeA"
channel_name = "Miko Ch. さくらみこ"
twitter = "sakuramiko35"
twitch = "sakuramiko_hololive"
aliases = ["miko", "mikoti", "mikocchi", "みこ", "みこっち"]

[[streamer]]
name = "Tokino Sora"
channel_id = "UCp6993wxpyDPHUpavwDFqgg"
channel_name = "SoraCh. ときのそらチャンネル"
twitter = "tokino_sora"
aliases = ["sora", "そら"]


# 1st Generation

[[streamer]]
name = "Akai Haato"
channel_id = "UC1CfXB_kRs3C-zaeTG3oGyg"
channel_name = "HAACHAMA Ch 赤井はあと"
twitter = "akaihaato"
twitch = "akaihaato_hololive"
aliases = ["haato", "haachama", "はあちゃま", "はあと"]

[[streamer]]
name = "Darkweb Haachama"
channel_id = "UCHj_mh57PVMXhAUDphUQDFA"
channel_name = "HAACHAMA DARKWEB CH"
twitter = "akaihaato"

[[streamer]]
name = "Shirakami Fubuki"
channel_id = "UCdn5BQ06XqgXoAxIhbqw5Rg"
channel_name = "フブキCh。白上フブキ"
twitter = "shirakamifubuki"
twitch = "shirakamifubuki_holo"
aliases = ["fubuki", "fbk", "フブキ"]

[[streamer]]
name = "Aki Rosenthal"
channel_id = "UCFTLzh12_nrtzqBPsTCqenA"
channel_name = "アキロゼCh。Vtuber/ホロライブ所属"
twitter = "akirosenthal"
twitch = "akirosenthal_hololive"
aliases = ["aki", "アキ"]

[[streamer]]
name = "Natsuiro Matsuri"
channel_id = "UCQ0UDLQCjY0rmuxCDE38FGg"
channel_name = "Matsuri Channel 夏色まつり"
twitter = "natsuiromatsuri"
twitch = "natsuiromatsuri_hololive"
aliases = ["matsuri", "まつり"]

[[streamer]]
name = "Aki Rosenthal (Sub)"
channel_id = "UCLbtM3JZfRTg8v2KGag-RMw"
channel_name = "AkiRose Ch.アキ・ローゼンタールSub"


# 2nd Generation

[[streamer]]
name = "Yuzuki Choco"
channel_id = "UC1suqwovbL1kzsoaZgFZLKg"
channel_name = "Choco Ch. 癒月ちょこ"
twitter = "yuzukichococh"
aliases = ["choco", "chocosen", "ちょこ"]

[[streamer]]
name = "Nakiri Ayame"
channel_id = "UC7fk0CB07ly8oSl0aqKkqFg"
channel_name = "Nakiri Ayame Ch. 百鬼あやめ"
twitter = "nakiriayame"
twitch = "nakiriayame_hololive"
aliases = ["ayame", "nakiri", "あやめ"]

[[streamer]]
name = "Oozora Subaru"
channel_id = "UCvzGlP9oQwU--Y0r9id_jnA"
channel_name = "Subaru Ch. 大空スバル"
twitter = "oozorasubaru"
aliases = ["subaru", "shuba", "スバル"]

[[streamer]]
name = "Choco Sub Channel"
channel_id = "UCp3tgHXw_HI0QMk1K8qh3gQ"
channel_name = "Choco subCh. 癒月ちょこ"


# GAMERS

[[streamer]]
name = "Inugami Korone"
channel_id = "UChAnqc_AY5_I3Px5dig3X1Q"
channel_name = "Korone Ch. 戌神ころね"
twitter = "inugamikorone"
aliases = ["korone", "korosan", "ころね", "ころさん"]

[[streamer]]
name = "Ookami Mio"
channel_id = "UCp-5t9SrOQwXMU7iIjQfARg"
channel_name = "Mio Channel 大神ミオ"
twitter = "ookamimio"
aliases = ["mio", "みお"]

[[streamer]]
name = "Nekomata Okayu"
channel_id = "UCvaTdHTWBGv3MKj3KVqJVCw"
channel_name = "Okayu Ch. 猫又おかゆ"
twitter = "nekomataokayu"
aliases = ["okayu", "おかゆ"]


# 3rd Generation (Fantasy)

[[streamer]]
name = "Usada Pekora"
channel_id = "UC1DCedRgGHBdm81E1llLhOQ"
channel_name = "Pekora Ch. 兎田ぺこら"
twitter = "usadapekora"
twitch = "usadapekora_hololive"
aliases = ["peko", "ペコ", "ぺこ"]

[[streamer]]
name = "Houshou Marine"
channel_id = "UCCzUftO8KOVkV4wQG1vkUvg"
channel_name = "Marine Ch. 宝鐘マリン"
twitter = "houshoumarine"
aliases = ["marine", "船長", "senchou", "sentyo", "mari-tan", "maripi"]

[[streamer]]
name = "Shirogane Noel"
channel_id = "UCdyqAaZDKHXg4Ahi7VENThQ"
channel_name = "Noel Ch. 白銀ノエル"
twitter = "shiroganenoel"
twitch = "shiroganenoel_hololive"
aliases = ["noel", "ノエル", "danchou", "団長"]

[[streamer]]
name = "Shiranui Flare"
channel_id = "UCvInZx9h3jC2JzsIzoOebWg"
channel_name = "Flare Ch. 不知火フレア"
twitter = "shiranuiflare"
twitch = "shiranuiflare_hololive"
aliases = ["flare", "フレア"]


# 4th Generation (holoForce)

[[streamer]]
name = "Tokoyami Towa"
channel_id = "UC1uv2Oq6kNxgATlCiez59hw"
channel_name = "Towa Ch. 常闇トワ"
twitter = "tokoyamitowa"
twitch = "tokoyamitowa_holo"
aliases = ["towa", "トワ"]

[[streamer]]
name = "Himemori Luna"
channel_id = "UCa9Y57gfeY0Zro_noHRVrnw"
channel_name = "Luna Ch. 姫森ルーナ"
twitter = "himemoriluna"
twitch = "himemoriluna_hololive"
aliases = ["ルーナ", "luna"]
free_chat_streams = true

[[streamer]]
name = "Tsunomaki Watame"
channel_id = "UCqm3BQLlJfvkTsX_hvm0UmA"
channel_name = "Watame Ch. 角巻わため"
twitter = "tsunomakiwatame"
twitch = "tsunomakiwatame_hololive"
aliases = ["watame", "わため"]


# 5th Generation (holoFive)

[[streamer]]
name = "Momosuzu Nene"
channel_id = "UCAWSyEs_Io8MtpY3m-zqILA"
channel_name = "Nene Ch.桃鈴ねね"
twitter = "momosuzunene"
twitch = "momosuzunene_hololive"
aliases = ["nene", "ねね", "nenechi"]
free_chat_streams = true

[[streamer]]
name = "Yukihana Lamy"
channel_id = "UCFKOVgVbGmX65RxO3EtH3iw"
channel_name = "Lamy Ch. 雪花ラミィ"
twitter = "yukihanalamy"
twitch = "yukihanalamy_hololive"
aliases = ["lamy", "らみ", "ラミィ"]

[[streamer]]
name = "Omaru Polka"
channel_id = "UCK9V2B22uJYu3N7eR_BT9QA"
channel_name = "Polka Ch. 尾丸ポルカ"
twitter = "omarupolka"
aliases = ["polka", "omaru", "ポル", "おまる", "omarun"]
free_chat_streams = true

[[streamer]]
name = "Shishiro Botan"
channel_id = "UCUKD-uaobj9jiqB-VXt71mA"
channel_name = "Botan Ch.獅白ぼたん"
twitter = "shishirobotan"
twitch = "shishirobotan_hololive"
aliases = ["botan", "ぼたん", "shishiron", "bossan"]


# 6th Generation -holoX-

[[streamer]]
name = "Laplus Darkness"
channel_id = "UCENwRMx5Yh42zWpzURebzTw"
channel_name = "Laplus ch. ラプラス・ダークネス - holoX -"
twitter = "LaplusDarknesss"
twitch = "laplusdarknesss_hololive"
aliases = ["Laplus"]

[[streamer]]
name = "Takane Lui"
channel_id = "UCs9_O1tRPMQTHQ-N_L6FU2g"
channel_name = "Lui ch. 鷹嶺ルイ - holoX -"
twitter = "takanelui"
twitch = "takanelui_hololive"
aliases = ["Lui"]

[[streamer]]
name = "Hakui Koyori"
channel_id = "UC6eWCld0KwmyHFbAqK3V-Rw"
channel_name = "Koyori ch. 博衣こより - holoX -"
twitter = "hakuikoyori"
twitch = "hakuikoyori_hololive"
aliases = ["Koyori"]

[[streamer]]
name = "Kazama Iroha"
channel_id = "UC_vMYWcDjmfdpH6r4TTn1MQ"
channel_name = "Iroha ch. 風真いろは - holoX -"
twitter = "kazamairohach"
twitch = "kazamairoha_holo"
aliases = ["Iroha"]


# ASOBI★MAWARI-TAI!

[[streamer]]
name = "Achichi Mela"
channel_id = "UC8eitCE9Z6EwUCs-VUi1blg"
channel_name = "Mela Ch. 熱千めら‐ アソビ★まわり隊!"
twitter = "achichi_mela"

[[streamer]]
name = "Sorashina Sopia"
channel_id = "UCROQtXcp2loQEmvpe5rhJzQ"
channel_name = "Sopia Ch. 宙科そぴあ ‐ アソビ★まわり隊!"
twitter = "sorashina_sopia"

[[streamer]]
name = "Hyakuto Kyoko"
channel_id = "UCSjQDxud2HkAO2DVD3lwxmw"
channel_name = "Kyoko Ch. 百灯キョーコ ‐ アソビ★まわり隊!"
twitter = "hyakuto_kyoko"

[[streamer]]
name = "Suzuna Tsuzuri"
channel_id = "UCy9mgxB8pn2C4aNK_MPthDQ"
channel_name = "Tsuzuri Ch. 鈴鳴つづり ‐ アソビ★まわり隊!"
twitter = "suzuna_tsuzuri"


# DEV_IS ReGLOSS

[[streamer]]
name = "Otonose Kanade"
channel_id = "UCWQtYtq9EOB4-I5P-3fh8lA"
channel_name = "Kanade Ch. 音乃瀬奏 ‐ ReGLOSS"
twitter = "otonosekanade"
aliases = ["Otonose", "Kanade"]

[[streamer]]
name = "Ichijou Ririka"
channel_id = "UCtyWhCj3AqKh2dXctLkDtng"
channel_name = "Ririka Ch. 一条莉々華 ‐ ReGLOSS"
twitter = "ichijouririka"
aliases = ["Ichijou", "Ririka"]

[[streamer]]
name = "Juufuutei Raden"
channel_id = "UCdXAk5MpyLD8594lm_OvtGQ"
channel_name = "Raden Ch. 儒烏風亭らでん ‐ ReGLOSS"
twitter = "juufuuteiraden"
aliases = ["Juufuutei", "Raden"]

[[streamer]]
name = "Todoroki Hajime"
channel_id = "UC1iA6_NT4mtAcIII6ygrvCw"
channel_name = "Hajime Ch. 轟はじめ ‐ ReGLOSS"
twitter = "todoroki_hajime"
aliases = ["Todoroki", "Hajime"]


# DEV_IS FLOW GLOW

[[streamer]]
name = "Isaki Riona"
channel_id = "UC9LSiN9hXI55svYEBrrK-tw"
channel_name = "Riona Ch. 響咲リオナ - FLOW GLOW"
twitter = "isakiriona"

[[streamer]]
name = "Kikirara Vivi"
channel_id = "UCGzTVXqMQHa4AgJVJIVvtDQ"
channel_name = "Vivi Ch. 綺々羅々ヴィヴィ - FLOW GLOW"
twitter = "kikiraravivi"

[[streamer]]
name = "Mizumiya Su"
channel_id = "UCjk2nKmHzgH5Xy-C5qYRd5A"
channel_name = "Su Ch. 水宮枢 - FLOW GLOW"
twitter = "mizumiya_su"

[[streamer]]
name = "Rindo Chihaya"
channel_id = "UCKMWFR6lAstLa7Vbf5dH7ig"
channel_name = "Chihaya Ch. 輪堂 千速 - FLOW GLOW"
twitter = "rindochihaya"

[[streamer]]
name = "Koganei Niko"
channel_id = "UCuI_opAVX6qbxZY-a-AxFuQ"
channel_name = "Niko Ch. 虎金妃笑虎 - FLOW GLOW"
twitter = "koganeiniko"


# mekPark

[[streamer]]
name = "ACHRORA"
channel_id = "UChpRPsAeSZn5DistGacR3iA"
channel_name = "ACHRORA - mekPark"
twitter = "ACHRORAofficial"


# Misc

[[streamer]]
name = "hololive Dreams"
channel_id = "UCawGfU44CZxd2ZVf_VGijbA"
channel_name = "hololive Dreams ホロライブドリームス"
twitter = "holo_dreams_en"

[[streamer]]
name = "Holoearth"
channel_id = "UCfpWrWvbA34LmrZ9h4Lbwag"
channel_name = "HOLOEARTH ホロアース"
twitter = "holoearth_en"

[[streamer]]
name = "hololive OFFICIAL CARD GAME"
channel_id = "UCmms2EE02mK4zdECwrHBpaA"
channel_name = "hololive OFFICIAL CARD GAME【公式】"
twitter = "hololive_OCG"

[[streamer]]
name = "Odeholo"
channel_id = "UCMyuwtApj--U6jm-NFzZMOw"
channel_name = "『おでかけホロライブ』アニメ公式チャンネル"
twitter = "odeholo"

[[streamer]]
name = "Midnight Grand Orchestra"
channel_id = "UCnVbtCwr-5LXxUlGxsgD7sQ"
twitter = "m_g_orchestra"

[[streamer]]
name = "holo indie"
channel_id = "UCt4-iv7EP0UU_w733D_r_jA"
channel_name = "holo Indie チャンネル"
twitter = "holoindie_ccmc"

[[streamer]]
name = "YAGOO"
channel_id = "UCu2DMOGLeR_DSStCyeQpi5Q"
channel_name = "tanigox"
twitter = "tanigox"
