[group]
id = "eien"
name = "EIEN"


# Official channels

[[streamer]]
name = "EIEN Project"
channel_id = "UC6zxNnx62SRBSYsbxP-rjsQ"
twitter = "EIENproj"


# Members

[[streamer]]
name = "Kiki Lockheart"
channel_id = "UCqfVP-d0Flj_ygWJ9m8gHMQ"
channel_name = "Kiki Lockheart Ch. 【EIEN Project】"
twitter = "KikiLockheart"
aliases = ["Kiki", "Lockheart"]

[[streamer]]
name = "Kilia Kurayami"
channel_id = "UCi6q0z8N1NNYgWPsM1OK25Q"
channel_name = "Kilia Kurayami Ch. 【EIEN Project】"
twitter = "KiliaKurayami"
aliases = ["Kilia", "Kurayami"]

[[streamer]]
name = "Skye Shinryu"
channel_id = "UC1tRqQTI3Bchs8XvUnj8yvQ"
channel_name = "Skye Shinryu Ch. 【EIEN Project】"
twitter = "SkyeShinryu"
aliases = ["Skye", "Shinryu"]

[[streamer]]
name = "Zumi Dokumi"
channel_id = "UCbvR46SQpOPRKMrVT8NoJTA"
channel_name = "Zumi Dokumi Ch. 【EIEN Project】"
twitter = "ZumiDokumi"
aliases = ["Zumi", "Dokumi"]

[[streamer]]
name = "Mirri Saffire"
channel_id = "UCz_8ztQ9rcu_UpUp0hv7bYw"
channel_name = "Mirri Saffire Ch. 【EIEN Project】"
twitter = "MirriSaffire"
aliases = ["Mirri", "Saffire"]

[[streamer]]
name = "Blaise Shinryu"
channel_id = "UCLdkcTt5vOfGi_myvK-iO0g"
channel_name = "Blaise Shinryu Ch. 【EIEN Project】"
twitter = "BlaiseShinryu"
aliases = ["Blaise", "Shinryu"]

[[streamer]]
name = "Amora Lumina"
channel_id = "UC0JFt5Jjl5a__zOaZLqk7Pg"
channel_name = "Amora Lumina Ch. 【EIEN Project】"
twitter = "AmoraLumina"
aliases = ["Amora", "Lumina"]

[[streamer]]
name = "Nanimo Navi"
channel_id = "UCxazidt7qQMNVW73wkpswOA"
channel_name = "Nanimo Navi Ch. 【EIEN Project】"
twitter = "NanimoNavi"
aliases = ["Nanimo", "Navi"]
