[group]
id = "idol"
name = "Idol"


# Official channels

[[streamer]]
name = "idol"
channel_id = "UCRMs0dRR4MEnCftyk6l1tvQ"
twitter = "idol_corp"


# Members

[[streamer]]
name = "Kattarina Qutie"
channel_id = "UCMmy_EmxnYQ8aar8fNZrumw"
channel_name = "Kattarina Qutie Ch. idol"
twitter = "kattarina_qutie"
aliases = ["Kattarina", "Qutie"]

[[streamer]]
name = "Nikki Rei"
channel_id = "UCBnmfjpmhGxao6v54fIIMUA"
channel_name = "Nikki Rei Ch. idol"
twitter = "nikki_rei_idol"
aliases = ["Nikki", "Rei"]

[[streamer]]
name = "Yuko Yurei"
channel_id = "UCcIcMRVpNqWQn4WnDhRASAw"
channel_name = "Yuko Yurei Ch. idol-EN"
twitter = "YureiYuko"
aliases = ["Yurei", "Yuko"]

[[streamer]]
name = "Juna Unagi"
channel_id = "UCTFCSCPvqjXEs3zq91aeOVg"
channel_name = "Juna Unagi Ch. idol-EN"
twitter = "JunaUnagi"
aliases = ["Juna", "Unagi"]

[[streamer]]
name = "Rin Penrose"
channel_id = "UCpZIbzoEC_3rZglErpQkbDg"
channel_name = "Rin Penrose Ch. idol-EN"
twitter = "RinPenrose"
aliases = ["Rin", "Penrose"]

[[streamer]]
name = "Fuyo Cloverfield"
channel_id = "UC8zgKaS8LiyL28mdhRC2nBg"
channel_name = "Fuyo Cloverfield Ch. idol-EN"
twitter = "FuyoCloverfield"
aliases = ["Fuyo", "Cloverfield"]

[[streamer]]
name = "Roca Rourin"
channel_id = "UC9xR7uN0x5a6CH3Uopq7czA"
channel_name = "Roca Rourin Ch. idol-EN"
twitter = "RocaRourin"
aliases = ["Roca", "Rourin"]

[[streamer]]
name = "Momo Otako"
channel_id = "UCe0JiGnjPfEwEIbWASbOimw"
channel_name = "Momo Otako Ch. idol-EN"
twitter = "MomoOtako"
aliases = ["Momo", "Otako"]

[[streamer]]
name = "Poko Rakun"
channel_id = "UCk2k1y-d24nFyVCvyxnAaYA"
channel_name = "Poko Rakun Ch. idol-EN"
twitter = "PokoRakun"
aliases = ["Poko", "Rakun"]

[[streamer]]
name = "Kai Saikota"
channel_id = "UCC4hjJp_MttwfZcuWc0OpVQ"
channel_name = "Kai Saikota Ch. idol-EN"
twitter = "KaiSaikota"
aliases = ["Kai", "Saikota"]

[[streamer]]
name = "Coni Confetti"
channel_id = "UCUfgKgCxtFs1ZPlyiM3JcTw"
channel_name = "Coni Confetti Ch. idol-EN"
twitter = "ConiConfetti"
aliases = ["Coni", "Confetti"]

[[streamer]]
name = "Akugaki Koa"
channel_id = "UC4R6ddhBJp2bjQHVNxgNQSA"
channel_name = "Akugaki Koa Ch. idol-ES"
twitter = "AkugakiKoa"
aliases = ["Akugaki", "Koa"]

[[streamer]]
name = "Ruby Runeheart"
channel_id = "UC-W-yaVIjqkXoh6dZ6_TcMA"
channel_name = "Ruby Runeheart Ch. idol-ES"
twitter = "RubyRuneheart"
aliases = ["Ruby", "Runeheart"]

[[streamer]]
name = "Lalabell Lullaby"
channel_id = "UCuDmUl3WY41FqGI_bUr62PA"
channel_name = "Lalabell Lullaby Ch. idol-ES"
twitter = "LalabellLullaby"
aliases = ["Lalabell", "Lullaby"]

[[streamer]]
name = "Taiga Toragami"
channel_id = "UCiBMH1d7ew_3bi2A_zZGsmw"
channel_name = "Taiga Toragami Ch. idol-ES"
twitter = "TaigaToragami"
aliases = ["Taiga", "Toragami"]

[[streamer]]
name = "Meica05"
channel_id = "UCp4G83RMBDN0EgZFSUDK7zw"
channel_name = "Meica05 Ch. idol-ES"
twitter = "Meica05"
aliases = ["Meica"]

[[streamer]]
name = "Enya Ignis"
channel_id = "UCBghUKA_L0na0SeQ6snzMMQ"
channel_name = "Enya Ignis Ch. idol-EN"
twitter = "EnyaIgnis"
aliases = ["Enya", "Ignis"]

[[streamer]]
name = "Shabel Tonya"
channel_id = "UCCA4jJY5PrTfIFJIcbI_NhQ"
channel_name = "Shabel Tonya Ch. idol-EN"
twitter = "ShabelTonya"
aliases = ["Shabel", "Tonya"]

[[streamer]]
name = "Chikafuji Lisa"
channel_id = "UCdureux7B_V-xhM7tYImASQ"
channel_name = "Chikafuji Lisa Ch. idol-EN"
twitter = "ChikafujiLisa"
aliases = ["Chikafuji", "Lisa"]
