[group]
id = "phase-connect"
name = "Phase Connect"


# Phase Connect

[[streamer]]
name = "Phase Connect JP"
channel_id = "UC6W1rDne4LOYK4XLpvhW6ow"
channel_name = "Phase Connect JP【公式】"
twitter = "PhaseConnectJP"

[[streamer]]
name = "Phase Connect"
channel_id = "UClpOEZoIYhxIY6n5NNGaPbA"
twitter = "PhaseConnect"


# Phase 01 - OriginS

[[streamer]]
name = "Ashelia Rinkou"
channel_id = "UCg7sW-h1PUowdiR5K4HlBew"
channel_name = "Lia Ch.【Phase Connect】"
twitter = "RinkouAshelia"
twitch = "asheliarinkou"
aliases = ["Ashelia", "Lia"]

[[streamer]]
name = "Utatane Nasa"
channel_id = "UCB7sSUNwh_dXE7ZL3DsGDpw"
channel_name = "Nasa Ch. 転寝ナサ 【Phase Connect】"
twitter = "UtataneNasa"
twitch = "utatanenasa"
aliases = ["Nasa", "Utatane"]

[[streamer]]
name = "Pipkin Pippa"
channel_id = "UCJ46YTYBQVXsfsp8-HryoUA"
channel_name = "Pipkin Pippa Ch.【Phase Connect】"
twitter = "pipkinpippa"
twitch = "pippa"
aliases = ["Pipkin", "Pippa"]

[[streamer]]
name = "Tenma Maemi"
channel_id = "UC3K7pmiHsNSx1y0tdx2bbCw"
channel_name = "Tenma Ch. マエミ 天満 【Phase Connect】"
twitter = "tenmamaemi"
twitch = "tenma"
aliases = ["Tenma", "Maemi"]

[[streamer]]
name = "Hakushika Iori"
channel_id = "UCN5bD1YYapThOeadG7YkBOA"
channel_name = "Iori Ch. 白鹿いおり【Phase Connect】"
twitter = "hakushikaiori"
twitch = "iorihakushika"
aliases = ["Iori", "Hakushika"]

[[streamer]]
name = "Fujikura Uruka"
channel_id = "UCjXJYPsKxoJyc-1RPB6dSyw"
channel_name = "Uruka Ch. 藤倉ウルカ 【Phase Connect】"
twitter = "fujikurauruka"
twitch = "fujikurauruka"
aliases = ["Uruka", "Fujikura"]

[[streamer]]
name = "Shisui Michiru"
channel_id = "UC1cExET9xoWSO9iSnRsW_1Q"
channel_name = "Michiru Ch. 紫翠みちる【Phase Connect】"
twitter = "shisuimichiru"
twitch = "michiru_shisui"
aliases = ["Michiru", "Shisui"]

[[streamer]]
name = "notPippa"
channel_id = "UCRW3qJuYP8aODl7_5TXn_nw"
twitter = "pipkinpippa"


# Phase Invaders

[[streamer]]
name = "Kaneko Lumi"
channel_id = "UCx_zwZuGIS4jxO07kFk8G6Q"
channel_name = "Lumi Ch.【Phase Connect】"
twitter = "Kaneko_Lumi"
twitch = "kanekolumi"
aliases = ["Lumi", "Kaneko"]

[[streamer]]
name = "Ember Amane"
channel_id = "UC0w_dvkIwnXzMak6gfeioRQ"
channel_name = "Ember Amane Ch. 【Phase Connect】"
twitter = "EmberAmane"
twitch = "emberamane"
aliases = ["Ember", "Amane"]

[[streamer]]
name = "Dizzy Dokuro"
channel_id = "UC98iRMvRqUxRD6GP4NtRskw"
channel_name = "Dizzy Dokuro Ch. 【Phase Connect】"
twitter = "dizzydokuro"
twitch = "dizzydokuro"
aliases = ["Dizzy", "Dokuro"]

[[streamer]]
name = "Hoshiumi Jelly"
channel_id = "UCkb-r702uhx4-6Lrmetp-Ow"
channel_name = "Jelly Hoshiumi Ch. 【Phase Connect】"
twitter = "jellyhoshiumi"
twitch = "jellyhoshiumi"
aliases = ["Jelly", "Hoshiumi"]


# Phase Invaders Quest

[[streamer]]
name = "Eepy Sleepy"
channel_id = "UC3aEtHpGzCFvoSn_wRWzgZQ"
channel_name = "Eepy Sleepy Ch. 【Phase Connect】"
twitter = "EepySleepyCh"
twitch = "eepysleepy"

[[streamer]]
name = "Mari Mari"
channel_id = "UCG5vZgELi3on_pksaLrIoxw"
channel_name = "Mari Mari Ch. [Phase Connect]"
twitter = "MARIMARI_EN"
twitch = "marimari_en"

[[streamer]]
name = "Clio Aite"
channel_id = "UCrGTSXWMiAWoPlowSuMVZ4Q"
channel_name = "Clio Ch. クリオ・アイテ [Phase Connect]"
twitter = "ClioAite"
twitch = "clioaite"


# Phase 02 - ALiAS

[[streamer]]
name = "Remilia Nephys"
channel_id = "UC-hMwvRuMsQrfgu0DPKLV2A"
channel_name = "Remilia Ch. レミリア・ネフィス 【Phase Connect】"
twitter = "Remilia_Nephys"
twitch = "remilianephys"
aliases = ["Remilia", "Nephys"]

[[streamer]]
name = "Chisaka Airi"
channel_id = "UC5qlAhrec6-0J-K3zmhNPPQ"
channel_name = "Airi Ch. 千坂 アイリ【Phase Connect】"
twitter = "ChisakaAiri"
twitch = "chisakaairi"
aliases = ["Airi", "Chisaka"]

[[streamer]]
name = "Amanogawa Shiina"
channel_id = "UCnJNNk45O1QYS2oMRYFKSyw"
channel_name = "Shiina Ch. 天ノ川 しいな 【Phase Connect】"
twitter = "AmanogawaShiina"
twitch = "amanogawashiina"
aliases = ["Shiina", "Amanogawa"]

[[streamer]]
name = "Himemiya Rie"
channel_id = "UCJ4O6PWA47f6XbCgrLQNqEQ"
channel_name = "Rie Ch. 姫宮りえ【Phase Connect】"
twitter = "HimemiyaRie"
twitch = "himemiyarie"
aliases = ["Rie", "Himemiya"]

[[streamer]]
name = "Erina Makina"
channel_id = "UCupmjRr7kPgzXKh-cPxxGbg"
channel_name = "Erina Ch. エリナ・マキナ 【Phase Connect】"
twitter = "ErinaMakina"
twitch = "erinamakina"
aliases = ["Erina", "Makina"]

[[streamer]]
name = "Komachi Panko"
channel_id = "UCVo_KgPNsDKxHwzib7uarCw"
channel_name = "Panko Ch. 小町ぱんこ 【Phase Connect】"
twitter = "komachipanko"
twitch = "komachipanko"
aliases = ["Panko", "Komachi"]

[[streamer]]
name = "Chisaka Airi's Twitch VODs"
channel_id = "UCx7aPMHI_kK1CP6zSvilHSA"
twitter = "ChisakaAiri"


# Phase 03 - Euphoria

[[streamer]]
name = "Muu Muyu"
channel_id = "UCejbicoRnQjCOdAPAv5JPwg"
channel_name = "Muyu Ch. むうむゆ【Phase Connect】"
twitter = "Muu_Muyu"
twitch = "muumuyu"

[[streamer]]
name = "Runie Ruse"
channel_id = "UCoAQsc-DQ0MjfTp059otQAw"
channel_name = "Runie Ch. ルニ・ルーズ【Phase Connect】"
twitter = "RunieRuse"
twitch = "runieruse"

[[streamer]]
name = "Eimi Isami"
channel_id = "UC-tBLCGTheczDn5mYNoNWTQ"
channel_name = "Eimi Ch. 勇エイミ【Phase Connect】"
twitter = "eimiisami"
twitch = "eimiisami"


# Phase 04 - SAGA

[[streamer]]
name = "Malice Evermore"
channel_id = "UC0mEc9OzI-B9HRi1v-GCVBw"
channel_name = "Malice Ch. マリス・エヴァーモア【Phase Connect】"
twitter = "MaliceEvermore"
twitch = "maliceevermore"

[[streamer]]
name = "Nitya Nil"
channel_id = "UCBXLH5mn0nxgFH3udMtw4ig"
channel_name = "Nitya Ch. 【Phase Connect】"
twitter = "Nitya_Nil"
twitch = "nitya_nil"

[[streamer]]
name = "Sinon Sinfonia"
channel_id = "UCjqlgGE9PA7xEbE6XW5Tl9g"
channel_name = "Sinon Ch.【Phase Connect】"
twitter = "SinonSinfonia"
twitch = "sinonsinfonia"

[[streamer]]
name = "Bibi Biscuit"
channel_id = "UCmbokzv5VTe9LeuzAFcDu9A"
channel_name = "Bibi Biscuit Ch.【Phase Connect】"
twitter = "BibiBiscuitCh"
twitch = "bibibiscuitch"

[[streamer]]
name = "Wilhelmina Frost"
channel_id = "UCzA7j_ixOvBz39saDYlbRiA"
channel_name = "Wilhelmina Ch.  ウィルヘルミナ・フロスト【Phase Connect】"
twitter = "wilhelminafr0st"
twitch = "wilhelminafrost"


# Phase JP - Kaleido

[[streamer]]
name = "Ayase Yuu"
channel_id = "UCnNLZWjl4GvVF4s8zBT9_kA"
channel_name = "Yuu Ch. 絢世ユウ 【Phase Connect】"
twitter = "ayaseyuuu"
twitch = "ayaseyuu_"

[[streamer]]
name = "Gram Pico"
channel_id = "UCtWH0tVAcUcSm4v96H5cAqQ"
channel_name = "Pico Ch. 倉夢ぴこ 【Phase Connect】"
twitter = "grampico_"
twitch = "grampico"

[[streamer]]
name = "Kannagi Loki"
channel_id = "UCucJYLJSEFRRfV2CA_JGHIQ"
channel_name = "Loki Ch. 巫ロキ 【Phase Connect】"
twitter = "kannagiloki"


# Other

[[streamer]]
name = "Hime's Basement"
channel_id = "UC3-Rfh_Ek-s6EUWS4fT5VPw"
twitter = "HimemiyaRie"

[[streamer]]
name = "Panko's tree house"
channel_id = "UCa_EIfw5I5uDlwsK6sc-83Q"
twitter = "komachipanko"

[[streamer]]
name = "Phase Music"
channel_id = "UCJ0fibMPM-kGU_Q1UVC1tHQ"
twitter = "PhaseConnect"

[[streamer]]
name = "KA-CHING!!"
channel_id = "UCvvl-93S0KFGDEXDjYuUquw"
