[group]
id = "v4mirai"
name = "V4Mirai"


# Official channels

[[streamer]]
name = "V4Mirai"
channel_id = "UCffASWaVk1PFnpC-gTvuJgw"
twitter = "V4Mirai"


# 2nd Gen Petalight

[[streamer]]
name = "Mono Monet"
channel_id = "UCdubotSy4pPOsiaW4MrYn3Q"
channel_name = "Mono Monet Ch.【V4Mirai】"
twitter = "mono_monet"
twitch = "monomonet"
aliases = ["Mono"]

[[streamer]]
name = "Yae Yugiri"
channel_id = "UCbDHIS0NpXROhYjsaXQX4pA"
channel_name = "Yae Yugiri Ch.【V4Mirai】"
twitter = "YaeYugiri"
twitch = "yaeyugiri"
aliases = ["Yae"]


# 3rd Gen Lunalia

[[streamer]]
name = "Dr Novae"
channel_id = "UC2Ne6dDcFxnM2hCBLii3IUg"
channel_name = "Dr.NOVA(e) Ch.【V4Mirai】"
twitter = "Dr_NOVAe"
twitch = "drnovae"
aliases = ["Novae", "Nova"]

[[streamer]]
name = "REM Kanashibari"
channel_id = "UCbZZlqASU668-wyW1K2kYBw"
channel_name = "REM Kanashibari Ch.【V4Mirai】"
twitter = "REMKanashibari"
twitch = "remkanashibari"
aliases = ["REM"]


# 4th Gen Voltail

[[streamer]]
name = "Lyko Lianna"
channel_id = "UC1nhjH-Jrh7GH9y0Fma-dGw"
channel_name = "Lyko Lianna Ch.【V4Mirai】"
twitter = "LykoLianna"
twitch = "lykolianna"

[[streamer]]
name = "Rara Rocora"
channel_id = "UCJmMPjJSRDOSfQKHHUs1efQ"
channel_name = "Rara Rocora Ch.【V4Mirai】"
twitter = "RaraRocora"
twitch = "rararocora"

[[streamer]]
name = "Poma Pon"
channel_id = "UCWChGhf3iYh9C_zAUNe9nag"
channel_name = "Poma Pon Ch.【V4Mirai】"
twitter = "pomapon_"
twitch = "pomapon_"


# 5th Gen AuraRain

[[streamer]]
name = "Paige Terner"
channel_id = "UCPet_g252gdu3R_jg4VP_ZQ"
channel_name = "Paige Terner Ch. 【V4Mirai】"
twitter = "paigeterner_"
twitch = "paigeterner_v4m"

[[streamer]]
name = "Ao WuWu"
channel_id = "UCXxakVxNmVfFEu1zuU9JmMQ"
channel_name = "Ao WuWu Ch.【V4Mirai】"
twitter = "_aowuwu"
twitch = "aowuwu_v4m"
