[group]
id = "vreverie"
name = "VReverie"


# Official channels

[[streamer]]
name = "VReverie Official"
channel_id = "UCfmwtHB52qFQaFFcKf-YMEw"
twitter = "VReverieLive"


# Members

[[streamer]]
name = "Nova Aokami"
channel_id = "UCA4bOB1Jnw5-lbuoSCfxc-w"
channel_name = "Nova Aokami Ch. [VReverie]"
twitter = "novavreverie"
aliases = ["Nova", "Aokami"]

[[streamer]]
name = "Ophelia Midnight"
channel_id = "UCZyNPQCjju3KIv9X84diljw"
channel_name = "Ophelia Midnight Ch. [VReverie]"
twitter = "opheliavreverie"
aliases = ["Ophelia", "Midnight"]

[[streamer]]
name = "Lilrya Prisvielle"
channel_id = "UCt7vm-7hlwPcYsRacX7QJYw"
channel_name = "Lilrya Prisvielle Ch. [VReverie]"
twitter = "lilryavreverie"
aliases = ["Lilrya", "Prisvielle"]

[[streamer]]
name = "Cheri Lupina"
channel_id = "UC70SZ3_zmeAgkj4JF-2kxYw"
channel_name = "Cheri Lupina Ch. [VReverie]"
twitter = "cherivreverie"
aliases = ["Cheri", "Lupina"]

[[streamer]]
name = "Rana Ianna"
channel_id = "UC-Y3evMx7MXbVeSbRKQ3gNw"
channel_name = "Rana Ianna Ch. [VReverie]"
twitter = "ranavreverie"
aliases = ["Rana", "Ianna"]

[[streamer]]
name = "Erika Byakko"
channel_id = "UC2jJc4BHQu-a0AVXkxlVL0w"
channel_name = "Erika Byakko Ch. [VReverie]"
twitter = "erikavreverie"
aliases = ["Erika", "Byakko"]

[[streamer]]
name = "Akiko Sushi"
channel_id = "UC-AgCrMaI3LYElHN-AbEiGw"
channel_name = "Akiko Sushi Ch. [VReverie]"
twitter = "akikovreverie"
aliases = ["Akiko", "Sushi"]
