[group]
id = "nijisanji-en"
name = "Nijisanji EN"
parent = "nijisanji"
order = 2


# Official channels

[[streamer]]
name = "NIJISANJI EN Official"
channel_id = "UC-JSeFfovhNsEhftt1WHMvg"
twitter = "NIJISANJI_World"
aliases = ["Nijisanji EN"]


# EN LazuLight

[[streamer]]
name = "Elira Pendora"
channel_id = "UCIeSUTOTkF9Hs7q3SGcO-Ow"
channel_name = "Elira Pendora 【NIJISANJI EN】"
twitter = "EliraPendora"
aliases = ["Elira", "Pendora", "Miss Pendora", "Ewiwa", "wiwi", "Ewiwi", "Eli"]

[[streamer]]
name = "Finana Ryugu"
channel_id = "UCu-J8uIXuLZh16gG-cT1naw"
channel_name = "Finana Ryugu 【NIJISANJI EN】"
twitter = "FinanaRyugu"
aliases = ["Finana", "Finaurnaur", "Ryugu"]


# EN OBSYDIA

[[streamer]]
name = "Petra Gurin"
channel_id = "UCgA2jKRkqpY_8eysPUs8sjw"
channel_name = "Petra Gurin【NIJISANJI EN】"
twitter = "Petra_Gurin"
aliases = ["Petra", "Gurin"]


# EN Ethyria

[[streamer]]
name = "Millie Parfait"
channel_id = "UC47rNmkDcNgbOcM-2BwzJTQ"
channel_name = "Millie Parfait【NIJISANJI EN】"
twitter = "MillieParfait"
twitch = "millieparfait"
aliases = ["Millie", "Parfait"]

[[streamer]]
name = "Enna Alouette"
channel_id = "UCR6qhsLpn62WVxCBK1dkLow"
channel_name = "Enna Alouette【NIJISANJI EN】"
twitter = "EnnaAlouette"
aliases = ["Enna", "Enner"]


# EN Luxiem

[[streamer]]
name = "Luca Kaneshiro"
channel_id = "UC7Gb7Uawe20QyFibhLl1lzA"
channel_name = "Luca Kaneshiro【NIJISANJI EN】"
twitter = "luca_kaneshiro"
twitch = "lucakaneshiro"
aliases = ["Pog-Man", "Lucy", "Luca"]

[[streamer]]
name = "Shu Yamino"
channel_id = "UCG0rzBZV_QMP4MtWg6IjhEA"
channel_name = "Shu Yamino【NIJISANJI EN】"
twitter = "shu_yamino"
aliases = ["Shu", "Yamino"]

[[streamer]]
name = "Vox Akuma"
channel_id = "UCckdfYDGrjojJM28n5SHYrA"
channel_name = "Vox Akuma【NIJISANJI EN】"
twitter = "Vox_Akuma"
aliases = ["Vox", "Akuma"]

[[streamer]]
name = "Luxiem Channel"
channel_id = "UCtHFXfrn52juTqGBN4WbMVw"
channel_name = "Luxiem Channel【NIJISANJI EN】"
twitter = "NIJISANJI_World"


# EN Noctyx

[[streamer]]
name = "Sonny Brisko"
channel_id = "UCuuAb_72QzK0M1USPMEl1yw"
channel_name = "Sonny Brisko 【NIJISANJI EN】"
twitter = "sonny_brisko"
aliases = ["Sonny", "Brisko"]

[[streamer]]
name = "Uki Violeta"
channel_id = "UChJ5FTsHOu72_5OVx0rvsvQ"
channel_name = "Uki Violeta 【NIJISANJI EN"
twitter = "uki_violeta"
twitch = "ukivioleta"
aliases = ["Uki", "Violeta"]

[[streamer]]
name = "Alban Knox"
channel_id = "UCQ1zGxHrfEmmW4CPpBx9-qw"
channel_name = "Alban Knox 【NIJISANJI EN"
twitter = "alban_knox"
aliases = ["Alban", "Knox"]


# EN ILUNA

[[streamer]]
name = "Maria Marionette"
channel_id = "UCwaS8_S7kMiKA3izlTWHbQg"
channel_name = "Maria Marionette 【NIJISANJI EN】"
twitter = "MariaMari0nette"
aliases = ["Maria", "Marionette"]

[[streamer]]
name = "Aia Amare"
channel_id = "UCN68LoM3khS4gdBMiWJO8WA"
channel_name = "Aia Amare 【NIJISANJI EN】"
twitter = "AiaAmare"
aliases = ["Aia", "Amare"]

[[streamer]]
name = "Scarle Yonaguni"
channel_id = "UCFgXWZOUZA2oYHNr6qDmsTQ"
channel_name = "Scarle Yonaguni 【NIJISANJI EN】"
twitter = "ScarleYonaguni"
aliases = ["Scarle", "Yonaguni"]

[[streamer]]
name = "Ren Zotto"
channel_id = "UCKu59gTZ_rdEmerdx5rV4Yg"
channel_name = "Ren Zotto 【NIJISANJI EN】"
twitter = "RenZott0"
aliases = ["Ren", "Zotto"]


# EN XSOLEIL

[[streamer]]
name = "Doppio Dropscythe"
channel_id = "UCy91xBlY_Brh3bnHxKtjrrg"
channel_name = "Doppio Dropscythe【NIJISANJI EN】"
twitter = "D_Dropscythe"
twitch = "doppiodropscythe"
aliases = ["Dropscythe", "Doppio"]

[[streamer]]
name = "Meloco Kyoran"
channel_id = "UChKXd7oqD18qiIYBoRIHTlw"
channel_name = "Meloco Kyoran【NIJISANJI EN】"
twitter = "MelocoKyoran"
twitch = "melocokyoran"
aliases = ["Meloco", "Kyoran"]

[[streamer]]
name = "Ver Vermillion"
channel_id = "UCO8WcDsF5znr-qsXlzZNpqg"
channel_name = "Ver Vermillion【NIJISANJI EN】"
twitter = "Ver_Vermillion"
aliases = ["Ver", "Vermillion"]


# EN Krisis

[[streamer]]
name = "Yu Q. Wilson"
channel_id = "UCKpKC3M5fkcEvtOr06dmYlA"
channel_name = "Yu Q. Wilson【NIJISANJI EN】"
twitter = "YuQWilson"
aliases = ["Yu", "Wilson"]

[[streamer]]
name = "Vantacrow Bringer"
channel_id = "UCpYf6C9QsP_BRf97vLuXlIA"
channel_name = "Vantacrow Bringer 【NIJISANJI EN】"
twitter = "Tyrant_Vanta"
twitch = "vantacrow_bringer"
aliases = ["Vantacrow", "Bringer"]

[[streamer]]
name = "Vezalius Bandage"
channel_id = "UCK9l6rTwU3hiSZijIMq51Gw"
channel_name = "Vezalius Bandage【NIJISANJI EN】"
twitter = "VezaliusBandage"
twitch = "vezalius_bandage"
aliases = ["Vezalius", "Bandage"]


# EN TTT

[[streamer]]
name = "Claude Clawmark"
channel_id = "UCdh-YF2gTzqDNu0VU9lwPPw"
channel_name = "Claude Clawmark【NIJISANJI EN】"
twitter = "ClaudeClawmark"
aliases = ["Claude", "Clawmark"]


# EN Denauth

[[streamer]]
name = "Ryoma Barrenwort"
channel_id = "UCIzZDiilcPv0wim_MbuizFA"
channel_name = "Ryoma Barrenwort【NIJISANJI EN】"
twitter = "RyomaBarrenwort"
aliases = ["Ryoma"]

[[streamer]]
name = "Klara Charmwood"
channel_id = "UCQYwIUCLqFoin7lHKmePjJw"
channel_name = "Klara Charmwood【NIJISANJI EN】"
twitter = "KlaraCharmwood"
aliases = ["Klara"]


# EN BY THE BEAT

[[streamer]]
name = "Seible"
channel_id = "UCCugV2RWXqJMjVVQl_Yh4TQ"
channel_name = "Seible【NIJISANJI EN】"
twitter = "Seible_2434"

[[streamer]]
name = "Kaelix Debonair"
channel_id = "UCEFOogmvTTcCaO8Qe0I8-tg"
channel_name = "Kaelix Debonair【NIJISANJI EN】"
twitter = "kaelixdebonair"

[[streamer]]
name = "Zeal Ginjoka"
channel_id = "UClMYGvekJOb51eBOCK-d4Dw"
channel_name = "Zeal Ginjoka【NIJISANJI EN】"
twitter = "zealginjoka"

[[streamer]]
name = "Freodore"
channel_id = "UCr40BzcLiGruKe7M5gXR9zQ"
channel_name = "Freodore【NIJISANJI EN】"
twitter = "Freo_2434"

[[streamer]]
name = "BY THE BEAT"
channel_id = "UCUEiLI0PQYewvAEtp6vEitA"
twitter = "by_the_beat"
