[group]
id = "nijisanji-id"
name = "Nijisanji ID"
parent = "nijisanji"
order = 3


# Ex-ID 3SetBBQ

[[streamer]]
name = "Hana Macchia"
channel_id = "UCpJtk0myFr5WnyfsmnInP-w"
channel_name = "Hana Macchia Ch.【NIJISANJI・にじさんじ】"
twitter = "Hana_Macchia"
aliases = ["Hana", "Macchia"]


# Ex-ID CloverMcOver

[[streamer]]
name = "Rai Galilei"
channel_id = "UC8Snw5i4eOJXEQqURAK17hQ"
channel_name = "Rai Galilei【NIJISANJI / にじさんじ】"
twitter = "Rai_Galilei"
aliases = ["Rai", "Galilei"]


# Ex-ID LAN_NEE3S

[[streamer]]
name = "Layla Alstroemeria"
channel_id = "UCyRkQSuhJILuGOuXk10voPg"
channel_name = "Layla Alstroemeria【NIJISANJI / にじさんじ】"
twitter = "LaylaAlstro2434"
twitch = "laylaalstroemeria"
aliases = ["Layla", "Alstroemeria"]


# Ex-ID 3FicLite

[[streamer]]
name = "Etna Crimson"
channel_id = "UCjFu-9GHnabzSFRAYm1B9Dw"
channel_name = "Etna Crimson【NIJISANJI / にじさんじ】"
twitter = "Etna_Crimson"
aliases = ["Etna", "Crimson"]


# Ex-ID 53Renade

[[streamer]]
name = "Nagisa Arcinia"
channel_id = "UCijNnZ-6m8g85UGaRAWuw7g"
channel_name = "Nagisa Arcinia【NIJISANJI・にじさんじ"
twitter = "NagisaArcinia"
aliases = ["Nagisa", "Arcinia"]

[[streamer]]
name = "Derem Kado"
channel_id = "UCMzVa7B8UEdrvUGsPmSgyjA"
channel_name = "Derem Kado 【にじさんじ / NIJISANJI】"
twitter = "DeremKado"
aliases = ["Derem", "Kado"]
