[group]
id = "nijisanji-kr"
name = "Nijisanji KR"
parent = "nijisanji"
order = 4


# Ex-KR First Wave

[[streamer]]
name = "Suha 민수하"
channel_id = "UCUtKkGKef8BYMs3h-3zQm9A"
channel_name = "민수하 /Suhaスハ【NIJISANJI】"
twitter = "SuhaMin2434"
twitch = "suha2434"
aliases = ["Suha", "민수하", "スハ"]

[[streamer]]
name = "GAON 가온"
channel_id = "UCpRXCTyNNa-MnjhK6gisnRw"
channel_name = "가온 ガオン GAON 【にじさんじ】"
twitter = "Gaon2434"
aliases = ["가온", "GAON", "ガオン"]


# Ex-KR Arashi Unagi

[[streamer]]
name = "ナギ / Nagi"
channel_id = "UC5ek2GWKvUKFgnKSHuuCFrw"
channel_name = "ナギ / Nagi 【にじさんじ】"
twitter = "NagiSo2434"
aliases = ["ナギ", "Nagi"]


# Ex-KR Neiro wa Murasaki

[[streamer]]
name = "LeeRoha"
channel_id = "UCClwIqTUn5LDpFucHyaAhHg"
channel_name = "イ・ロハ / LeeRoha【にじさんじ】"
twitter = "RohaLee2434"
aliases = ["イ・ロハ"]

[[streamer]]
name = "Akira Ray"
channel_id = "UC7hffDQLKIEG-_zoAQkMIvg"
channel_name = "明楽 レイ /아키라 레이 / Ray Akira 【にじさんじ】"
twitter = "RayAkira2434"


# Ex-KR Fourth Wave

[[streamer]]
name = "Yang Nari"
channel_id = "UCCHH0nWYXFZmtDS_4tvMxHQ"
channel_name = "ヤン・ナリ / Yang Nari 【にじさんじ】"
twitter = "NariYang2434"
twitch = "nariyang2434"
aliases = ["Yang", "Nari", "ヤン・ナリ", "ヤン"]

[[streamer]]
name = "Ryu Hari"
channel_id = "UClS6k3w1sPwlVFqK3-yID5A"
channel_name = "ハリ / Ryu Hari 【にじさんじ】"
twitter = "HariRyu2434"
aliases = ["Ryu", "Hari", "ハリ"]

[[streamer]]
name = "ジユ / Jiyu"
channel_id = "UCnzZmBOSrQf2wDBbnsDajVw"
channel_name = "ジユ / Jiyu 【にじさんじ】"
twitter = "JiyuOh2434"
aliases = ["ジユ", "Jiyu"]


# Ex-KR Mianhada Pinaya

[[streamer]]
name = "Seffyna"
channel_id = "UCeGendL8CO5RkffB6IFwHow"
channel_name = "セフィナ / Seffyna【にじさんじ】"
twitter = "Seffyna2434"
aliases = ["セフィナ"]


# Ex-KR Sixth Wave

[[streamer]]
name = "Na Sera"
channel_id = "UCX88Pe54pxbJDSGIyGrzNdg"
channel_name = "ナ セラ / Na Sera【にじさんじ】"
twitter = "NaSera2434"
aliases = ["Sera"]

[[streamer]]
name = "HaYun"
channel_id = "UCrhhJPNsOqzNIkUfTABoSpg"
channel_name = "ハユン / HaYun 【にじさんじ】"
twitter = "HaYun2434"
aliases = ["ハユン"]
